language: php
dist: bionic

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1

env:
  global:
    - USER=travis
    - PASS=travis

matrix:
#  allow_failures:
#    - php: 5.5

before_script:
  - echo "travis:travis" | sudo chpasswd
  # Prepare Composer
  - composer self-update || true
  - composer update
  - composer --prefer-source --dev update

script:
  # Reset CUPS and PDF Printer
  - sudo apt-get remove -yqq cups cups-pdf
  - sudo apt-get install -yqq cups cups-pdf cups-client
  - sudo adduser travis lpadmin
  - sudo service cups restart
  # Test PDF Printer
  - which lp
  - lp -d PDF LICENSE && sleep 10
  # Run Tests
  - ./vendor/bin/atoum -d tests/ -ncc -utr
